#pragma once

#include "abi.h"
#include "common.h"
#include "gcc2.h"

struct MotionBlock;
struct TaggedValue;

// The development tools' arguments of a command, which each command's ParseTokens (its vtable's slot 2) reads into its fields:
// the retail game never parses any. A token is its tag (the argument it gives, TagNone for a bare value), what its value is
// (ScriptTokenType) and the value: a float's or an integer's bits, a keyword or an instance property's index

// The AgentLab tool's tags (its LABTAGs, the arguments' names), named as the tool's lists name them where they fit what the game
// does with them (the lists stop at 0x9E and 0x230; their abbreviations spelt out) and the game's own after what they set. The
// Unused ones only fill fields nothing reads
enum ScriptTag : u16
{
    // The tool's list
    TagX = 0x0,
    TagY = 0x1,
    TagZ = 0x2,
    TagPitch = 0x3,
    TagYaw = 0x4,
    TagRoll = 0x5,
    // A starter receiver's index
    TagAgent = 0x6,
    // A key, counted from 1
    TagKey = 0x7,
    TagStart = 0x8,
    TagEnd = 0x9,
    TagCount = 0xA,
    TagVolume = 0xB,
    TagDuration = 0xC,
    TagRed = 0xD,
    TagGreen = 0xE,
    TagBlue = 0xF,
    // An object's ID
    TagActor = 0x10,
    // An animation slot (an icon's too)
    TagAnimation = 0x11,
    TagExitPoint = 0x12,
    TagModel = 0x13,
    TagBlendSeconds = 0x14,
    TagParticle = 0x15,
    TagSound = 0x16,
    TagDecal = 0x17,
    TagAcceleration = 0x18,
    TagVelocity = 0x19,
    TagInterval = 0x1A,
    TagScalar = 0x1B,
    TagTurn = 0x1C,
    TagXWave = 0x1D,
    TagYWave = 0x1E,
    TagZWave = 0x1F,
    TagXMagnitude = 0x20,
    TagYMagnitude = 0x21,
    TagZMagnitude = 0x22,
    TagXTime = 0x23,
    TagYTime = 0x24,
    TagZTime = 0x25,
    TagXPhase = 0x26,
    TagYPhase = 0x27,
    TagZPhase = 0x28,
    TagXDisplacement = 0x29,
    TagYDisplacement = 0x2A,
    TagZDisplacement = 0x2B,
    TagXWay = 0x2C,
    TagYWay = 0x2D,
    TagZWay = 0x2E,
    TagDelay = 0x2F,
    TagEnergy = 0x30,
    TagTumble = 0x31,
    TagTumbleSpeed = 0x32,
    TagTwist = 0x33,
    TagTwistSpeed = 0x34,
    TagSpin = 0x35,
    TagSpinSpeed = 0x36,
    TagWorldSpinSpeed = 0x37,
    TagDegreesPerSecond = 0x38,
    TagMetresPerSecond = 0x39,
    TagAccelerationDistance = 0x3A,
    TagDecelerationDistance = 0x3B,
    TagTolerance = 0x3C,
    TagTo = 0x3D,
    TagPower = 0x3E,
    TagDamping = 0x3F,
    TagSpeedLimit = 0x40,
    TagRise = 0x41,
    TagRandomXPhase = 0x42,
    TagRandomYPhase = 0x43,
    TagRandomZPhase = 0x44,
    TagSurface = 0x45,
    TagApplyX = 0x46,
    TagApplyY = 0x47,
    TagApplyZ = 0x48,
    TagVelocityX = 0x49,
    TagVelocityY = 0x4A,
    TagVelocityZ = 0x4B,
    TagDistanceX = 0x4C,
    TagDistanceY = 0x4D,
    TagDistanceZ = 0x4E,
    TagJoint = 0x4F,
    TagBend = 0x50,
    TagBendSpeed = 0x51,
    TagSwing = 0x52,
    TagSwingSpeed = 0x53,
    TagXClip = 0x54,
    TagYClip = 0x55,
    TagZClip = 0x56,
    TagYRaise = 0x57,
    TagKeyLocal = 0x58,
    TagScale = 0x59,
    TagMinKey = 0x5A,
    TagMaxKey = 0x5B,
    TagThreshold = 0x5C,
    TagIfSurface = 0x5D,
    // The tool's retired ZZZ_ACTIVE
    TagRestartable = 0x5E,
    TagRetiredVisible = 0x5F,
    TagRetiredCollidable = 0x60,
    TagState = 0x61,
    TagMaxNodes = 0x62,
    TagSharpTurn = 0x63,
    TagPriority = 0x64,
    TagRange = 0x65,
    // A rigid body's kind of motion
    TagAgentPairs = 0x66,
    // A rigid body's kind of collisions with the world
    TagTerrain = 0x67,
    TagLogicalRadius = 0x68,
    TagNavigationRadius = 0x69,
    TagGravity = 0x6A,
    TagToExitPoint = 0x6B,
    TagBehaviour = 0x6C,
    TagMessage = 0x6D,
    TagCounter = 0x6E,
    TagSubtype = 0x6F,
    // A behaviour slot (the tool's FSM)
    TagBehaviourSlot = 0x70,
    TagResidentActor = 0x71,
    // A linked object's index, counted from 1
    TagLinked = 0x72,
    TagFriction = 0x73,
    TagBounce = 0x74,
    TagDiveDegreesPerSecond = 0x75,
    TagElevation = 0x76,
    TagZoom = 0x77,
    TagHomingPower = 0x78,
    TagInertia = 0x79,
    TagTurnLimit = 0x7A,
    TagHoldingActor = 0x7B,
    TagExitHold = 0x7C,
    TagExitFree = 0x7D,
    TagBusy = 0x7E,
    TagRender = 0x7F,
    TagCollide = 0x80,
    TagUpdate = 0x81,
    TagXShift = 0x82,
    TagYShift = 0x83,
    TagZShift = 0x84,
    TagSoftFlag = 0x85,
    TagLandable = 0x86,
    TagMaxTilt = 0x87,
    TagTiltPower = 0x88,
    TagChildActor = 0x89,
    TagBecome = 0x8A,
    TagAntiRoll = 0x8B,
    TagSpringPower = 0x8C,
    TagSpringDamping = 0x8D,
    TagVibrate = 0x8E,
    TagSteady = 0x8F,
    TagFlatMultiplier = 0x90,
    TagCluster = 0x91,
    TagSoundBank = 0x92,
    TagEffect = 0x93,
    TagRepelForce = 0x94,
    TagSyncTo = 0x95,
    TagRandomVolume = 0x96,
    TagRandomPitch = 0x97,
    TagRelativePitch = 0x98,
    TagScrew = 0x99,
    TagTune = 0x9A,
    TagLodBoost = 0x9B,
    TagYMultiplier = 0x9C,
    TagCopyState = 0x9D,
    TagPitchScalar = 0x9E,

    // The game's own
    TagSpinY = 0x9F,
    TagSpinX = 0xA0,
    TagGrabStrength = 0xA1,
    TagUnusedA2 = 0xA2,
    TagUnusedA3 = 0xA3,
    TagHoldStrength = 0xA4,
    TagStiffness = 0xA5,
    // A route's weight of keeping away from the focus, a cover search's box half width
    TagAvoidFocus = 0xA6,
    // A route's weight of keeping near the focus, a cover search's weight of a position's exposure
    TagNearFocus = 0xA7,
    TagDistanceWeight = 0xA8,
    TagCylinderHeight = 0xA9,
    TagRouteCorner = 0xAA,
    TagRouteToward = 0xAB,
    TagRouteScatter = 0xAC,
    TagPositionCostWeight = 0xAD,
    TagHalfHeight = 0xAE,
    // On clears the AI position's blocked flag, Off sets it
    TagPointPassable = 0xAF,
    TagPointAirborne = 0xB0,
    TagPointAlwaysTaken = 0xB1,
    TagAgentCounter = 0xB2,
    TagHeadJoint = 0xB3,
    TagSecondHeadJoint = 0xB4,
    TagNegativePitchLimit = 0xB5,
    TagPositivePitchLimit = 0xB6,
    TagYawLimit = 0xB7,
    TagTrackingStiffness = 0xB8,
    TagUnusedB9 = 0xB9,
    TagUnusedBA = 0xBA,
    TagUnusedBB = 0xBB,
    TagUnusedBC = 0xBC,
    TagUnusedBD = 0xBD,
    TagUnusedBE = 0xBE,
    TagUnusedBF = 0xBF,
    // A noise's loudness, a head tracking target's weight
    TagLoudness = 0xC2,
    TagValue = 0xC3,
    TagAddedRise = 0xC5,
    TagAhead = 0xC6,
    TagSourceDesignator = 0xC7,
    TagDestinationDesignator = 0xC8,
    TagModelDistance = 0xC9,
    TagNodeDistance = 0xCA,
    TagRunnerSlot = 0xCB,
    TagMagnetPull = 0xCC,
    // A radius, a width or a distance
    TagSize = 0xCD,
    TagKnockScale = 0xCE,
    TagRank = 0xCF,
    TagSlowingX = 0xD0,
    TagSlowingY = 0xD1,
    TagSlowingZ = 0xD2,
    TagSenseDivisor = 0xD3,
    TagSenseDecay = 0xD4,
    // A sense's weight, a presence
    TagPerceptionWeight = 0xD5,
    TagRate = 0xD6,
    TagAlongPerception = 0xD7,
    // A sense's seconds between steps, a swinging camera's phase scale
    TagSenseInterval = 0xD8,
    TagLowest = 0xD9,
    TagHighest = 0xDA,
    TagSpeedScale = 0xDB,
    TagAmplitudeX = 0xDC,
    TagAmplitudeY = 0xDD,
    TagAmplitudeZ = 0xDE,
    TagShakeX = 0xE0,
    TagShakeY = 0xE1,
    TagShakeStrength = 0xE2,
    TagShakeFalloff = 0xE4,
    TagTrailProgress = 0xE5,
    TagWidth = 0xE6,
    TagHeight = 0xE7,
    TagDepth = 0xE8,
    TagText = 0xE9,
    TagMoveSpeed = 0xEA,
    TagUnusedEB = 0xEB,
    TagSourceAgent = 0xEC,
    TagLength = 0xED,
    TagFocusJoint = 0xEE,
    TagImpulseCap = 0xEF,
    TagFixedImpulse = 0xF0,
    TagXMultiplier = 0xF1,
    TagZMultiplier = 0xF2,
    TagTurnToFocus = 0xF3,
    TagFocusCounter = 0xF4,
    TagGameCounter = 0xF5,
    TagCounterIndex = 0xF6,
    TagStartRange = 0xF7,
    TagEndRange = 0xF8,
    TagSubsteps = 0xF9,
    TagFieldWidth = 0xFA,
    TagField = 0xFB,
    TagFieldBits = 0xFC,
    TagMass = 0xFD,
    TagTrailStrength = 0xFE,
    TagRouteSideways = 0xFF,
    TagRouteLift = 0x100,
    // The same as TagRouteToward
    TagRouteForward = 0x101,
    TagHull = 0x102,
    TagEdgePush = 0x103,
    TagFromDesignator = 0x104,
    TagToDesignator = 0x105,
    TagAlongDistance = 0x106,
    TagFirstTarget = 0x107,
    TagSecondTarget = 0x108,
    TagCrouchedSpeed = 0x10B,
    TagTopSpeed = 0x10C,
    TagExtraDistance = 0x10D,
    TagAwayFromPlayer = 0x10E,
    TagRandomBelow = 0x10F,
    TagFirstTargetPosition = 0x110,
    TagSecondTargetPosition = 0x111,
    TagExtraHeight = 0x114,
    TagCameraYaw = 0x115,
    TagRandomInterval = 0x116,
    TagAgentDesignator = 0x117,
    TagCutscene = 0x11A,
    TagLeadSeconds = 0x11B,
    TagStartPosition = 0x11C,
    TagFeedback = 0x11E,
    TagReverbDepth = 0x11F,
    TagPushable = 0x120,
    // The physics body's other pushable bit
    TagPushableToo = 0x121,
    TagShadowSlot = 0x122,
    TagShadowDistance = 0x123,
    TagNearStrength = 0x124,
    TagFarStrength = 0x125,
    TagShadowJoint = 0x126,
    TagShadowSecondJoint = 0x127,
    TagDecals = 0x128,
    TagFirstContactSound = 0x129,
    TagLastContactSound = 0x12A,
    TagPositionJoint = 0x12B,
    TagBuoyancy = 0x12C,
    TagCarries = 0x12D,
    TagRangeEnd = 0x12E,
    TagRangeFirst = 0x12F,
    TagAngle = 0x132,
    TagFirstWeaponJoint = 0x133,
    TagSecondWeaponJoint = 0x134,
    TagThirdWeaponJoint = 0x135,
    TagCountedValue = 0x136,
    TagRumble = 0x137,
    TagSolid = 0x138,
    TagTargetPath = 0x139,
    TagCameraPath = 0x13A,
    TagTargetAlong = 0x13B,
    TagCameraAlong = 0x13C,
    TagUnused13D = 0x13D,
    TagDrop = 0x13E,

    // The tool's custom ones (its FIRST_CUSTOM_LTID on) and the game's after them
    TagQuantity = 0x200,
    TagRedWumpaActor = 0x201,
    TagHealthActor = 0x202,
    // The tool's FRAGMENT_ACTOR
    TagPlayerMode = 0x203,
    TagHitPoints = 0x204,
    TagRadius = 0x205,
    TagDamageType = 0x206,
    TagActive = 0x207,
    TagVisible = 0x208,
    TagShadow = 0x209,
    TagTangible = 0x20A,
    TagCollidable = 0x20B,
    TagBouncy = 0x20C,
    TagInput = 0x20D,
    TagRedWumpaCount = 0x20E,
    TagClamping = 0x20F,
    TagSelectable = 0x210,
    TagWallRadius = 0x211,
    TagCliffRadius = 0x212,
    TagWallShy = 0x213,
    TagCliffShy = 0x214,
    TagCustomYRaise = 0x215,
    TagHarmful = 0x216,
    // The tool's SELF_HARMING
    TagInstantDeath = 0x217,
    TagMinRedWumpa = 0x218,
    TagMaxRedWumpa = 0x219,
    TagFlank = 0x21A,
    TagExplore = 0x21B,
    TagWumpaHover = 0x21C,
    TagChainSuck = 0x21D,
    TagSuckRange = 0x21E,
    TagSuckPower = 0x21F,
    TagHitCrates = 0x220,
    TagHitCreatures = 0x221,
    TagHitFurniture = 0x222,
    TagHitPlayer = 0x223,
    TagHitScenery = 0x224,
    TagHitAgents = 0x225,
    TagHitAll = 0x226,
    TagFlySpeed = 0x227,
    TagHitPickups = 0x228,
    TagRotation = 0x229,
    TagForwardMovement = 0x22A,
    TagLateralMovement = 0x22B,
    TagJumpKey = 0x22C,
    TagCrouchKey = 0x22D,
    TagSpinKey = 0x22E,
    // The tool's FOOFIEKEY
    TagLives = 0x22F,
    TagAffectedByGravity = 0x230,
    TagUnused231 = 0x231,
    TagUnused232 = 0x232,
    TagUnused233 = 0x233,
    TagUnused234 = 0x234,
    TagUnused235 = 0x235,
    TagDamageHull = 0x236,
    TagVulnerable = 0x237,
    TagBulletsBounceBack = 0x238,
    TagCharacter = 0x239,
    TagStickStrength = 0x23A,
    TagSaves = 0x23B,
    TagSpinAttack = 0x23C,
    TagUnused23D = 0x23D,
    TagSlamAttack = 0x23E,
    TagWalkIntoAttack = 0x23F,
    TagUnused240 = 0x240,
    TagTargetSeconds = 0x241,
    TagCameraSeconds = 0x242,
    TagAttentionWeight = 0x243,
    TagTargettable = 0x244,
    TagUnused245 = 0x245,
    TagUnused246 = 0x246,
    TagFov = 0x247,
    TagSecondCharacter = 0x248,
    TagFirstCharacter = 0x249,

    // A bare value (a keyword or a number) without a tag
    TagNone = 0xFFFF,
};

// The AgentLab tool's keywords (its LABVALs), a token's value when its type is TokenKeyword, named the same way (the tool's lists
// stop at 0x73 and 0x215)
enum ScriptKeyword : u32
{
    // The tool's list
    KeywordOn = 0x0,
    KeywordOff = 0x1,
    KeywordWorldSpace = 0x2,
    KeywordInitialSpace = 0x3,
    KeywordCurrentSpace = 0x4,
    KeywordTargetSpace = 0x5,
    KeywordAgentRegister = 0x6,
    KeywordRegionRegister = 0x7,
    KeywordLevelRegister = 0x8,
    KeywordGameRegister = 0x9,
    KeywordTwoD = 0xA,
    KeywordThreeD = 0xB,
    KeywordLooped = 0xC,
    KeywordSticky = 0xD,
    KeywordGlobal = 0xE,
    KeywordAlways = 0xF,
    KeywordSine = 0x10,
    KeywordSquare = 0x11,
    KeywordTriangle = 0x12,
    KeywordRandom = 0x13,
    KeywordIn = 0x14,
    KeywordOut = 0x15,
    KeywordAngular = 0x16,
    KeywordOrient = 0x17,
    KeywordQuestionMark = 0x18,
    KeywordParentSpace = 0x19,
    KeywordScaleJoint = 0x1A,
    KeywordTilt = 0x1B,
    KeywordFocus = 0x1C,
    KeywordFocusPosition = 0x1D,
    KeywordPositive = 0x1E,
    KeywordNegative = 0x1F,
    KeywordSelf = 0x20,
    KeywordStoredSpace = 0x21,
    KeywordSpin = 0x22,
    KeywordExitSpace = 0x23,
    KeywordCurrentKey = 0x24,
    KeywordNextKey = 0x25,
    KeywordForward = 0x26,
    KeywordBack = 0x27,
    KeywordLeft = 0x28,
    KeywordRight = 0x29,
    KeywordUp = 0x2A,
    KeywordDown = 0x2B,
    // The route's current step
    KeywordCurrentNode = 0x2C,
    // The route's next step, moved on to
    KeywordNextNode = 0x2D,
    KeywordStop = 0x2E,
    KeywordDefault = 0x2F,
    KeywordPush = 0x30,
    KeywordSphere = 0x31,
    KeywordCuboid = 0x32,
    KeywordSimplex = 0x33,
    KeywordEnclosingSphere = 0x34,
    KeywordRayDrop = 0x35,
    KeywordNatural = 0x36,
    KeywordContingent = 0x37,
    KeywordSnapNearFace = 0x38,
    KeywordRandomChoice = 0x39,
    KeywordInfiniteMass = 0x3A,
    KeywordAxisBox = 0x3B,
    KeywordAttach = 0x3C,
    KeywordFirst = 0x3D,
    KeywordAll = 0x3E,
    KeywordJustVertical = 0x3F,
    KeywordFullMotion = 0x40,
    KeywordNoPhysicsMotion = 0x41,
    KeywordAutoRevert = 0x42,
    KeywordClampNormal = 0x43,
    KeywordCentre = 0x44,
    KeywordContact = 0x45,
    KeywordWithMass = 0x46,
    KeywordHoldSomething = 0x47,
    KeywordHoldNothing = 0x48,
    KeywordHeld = 0x49,
    KeywordUnheld = 0x4A,
    KeywordIdle = 0x4B,
    KeywordBusy = 0x4C,
    KeywordMakeBusy = 0x4D,
    KeywordMakeIdle = 0x4E,
    KeywordFixed = 0x4F,
    KeywordJustMove = 0x50,
    KeywordSimpleChain = 0x51,
    KeywordTrail = 0x52,
    KeywordWobble = 0x53,
    KeywordCollider = 0x54,
    KeywordNothing = 0x55,
    KeywordMaster = 0x56,
    KeywordSlave = 0x57,
    KeywordBall = 0x58,
    KeywordWheel = 0x59,
    KeywordCornerSprings = 0x5A,
    KeywordFreeSphere = 0x5B,
    KeywordFreeCuboid = 0x5C,
    KeywordResnap = 0x5D,
    KeywordZonal = 0x5E,
    KeywordNodal = 0x5F,
    KeywordHard = 0x60,
    KeywordSoft = 0x61,
    KeywordCentral = 0x62,
    KeywordApplyReverb = 0x63,
    KeywordApplyEcho = 0x64,
    KeywordApplyChorus = 0x65,
    KeywordApplyPhase = 0x66,
    KeywordFx1 = 0x67,
    KeywordFx2 = 0x68,
    KeywordSpeech = 0x69,
    KeywordMusic = 0x6A,
    KeywordSpaceRotation = 0x6B,
    KeywordMakeLinked = 0x6C,
    KeywordForever = 0x6D,
    KeywordInert = 0x6E,
    KeywordOneWay = 0x6F,
    KeywordSmoothMagnitude = 0x70,
    KeywordContext = 0x71,
    KeywordArea = 0x72,
    KeywordMakeFocus = 0x73,

    // The game's own
    KeywordAgentRef1 = 0x74,
    KeywordAgentRef2 = 0x75,
    KeywordUnused76 = 0x76,
    KeywordMakeAgentRef2 = 0x77,
    KeywordPassAgentRef1 = 0x79,
    KeywordStoredPosition = 0x7A,
    KeywordUnused7B = 0x7B,
    KeywordTrackedSpace = 0x7C,
    KeywordFaceTracked = 0x7D,
    KeywordUprightLaunched = 0x7F,
    KeywordHoldTouched = 0x80,
    KeywordHoldAgentRef1 = 0x81,
    KeywordPlayersShot = 0x82,
    KeywordSearchInBox = 0x83,
    KeywordFromOriginator = 0x85,
    KeywordLinkSpawner = 0x87,
    KeywordPlayer = 0x88,
    KeywordOriginator = 0x89,
    // An upright cylinder's motion, an upright ellipsoid's collisions
    KeywordUpright = 0x8A,
    // Pushed away from the instances around, slid out by its friction
    KeywordSlide = 0x8D,
    KeywordUnused8E = 0x8E,
    KeywordHeadTarget = 0x8F,
    KeywordUnusedDesignator90 = 0x90,
    KeywordUnusedDesignator91 = 0x91,
    KeywordConstraintFixed = 0x92,
    KeywordLineX = 0x93,
    KeywordLineY = 0x94,
    KeywordLineZ = 0x95,
    KeywordPlaneY = 0x96,
    KeywordPlaneZ = 0x97,
    KeywordPlaneX = 0x98,
    KeywordHingeX = 0x99,
    KeywordHingeY = 0x9A,
    KeywordHingeZ = 0x9B,
    KeywordShareFocus = 0x9C,
    KeywordShareStoredPosition = 0x9D,
    KeywordShareAgentRef2 = 0x9F,
    KeywordToFocus = 0xA0,
    KeywordInitialPosition = 0xA1,
    KeywordNoCollisions = 0xA2,
    KeywordToTheRight = 0xA3,
    KeywordToTheLeft = 0xA4,
    KeywordCurrentLinked = 0xA5,
    KeywordMagnetMode2 = 0xA7,
    KeywordEven = 0xA8,
    KeywordFromBody = 0xA9,
    KeywordAlongZAxis = 0xAA,
    KeywordShareLinked = 0xAB,
    KeywordCastRay = 0xAC,
    KeywordSenseInstances = 0xAD,
    KeywordSenseRising = 0xAE,
    KeywordSenseSpeed = 0xAF,
    KeywordIgnoreSignals = 0xB0,
    // The route's next step, not moved on to
    KeywordNextStep = 0xB1,
    KeywordPerception = 0xB2,
    // A sense kind nothing makes
    KeywordUnusedSense = 0xB3,
    KeywordPadDriven = 0xB4,
    KeywordMotionDriven = 0xB5,
    KeywordUpdateOnce = 0xB6,
    KeywordNoUpdate = 0xB7,
    KeywordKeepX = 0xB8,
    KeywordKeepY = 0xB9,
    KeywordKeepZ = 0xBA,
    KeywordShadowCylinder = 0xBB,
    KeywordShadowRoundedCube = 0xBC,
    KeywordShadowCube = 0xBD,
    KeywordShadowOctagon = 0xBE,
    KeywordAlongX = 0xBF,
    KeywordAlongY = 0xC0,
    KeywordAlongZ = 0xC1,
    KeywordNoRepeat = 0xC2,
    KeywordUnlink = 0xC3,
    KeywordLast = 0xC4,
    KeywordOfFocus = 0xC5,
    KeywordOfAgentRef1 = 0xC6,
    KeywordRadiusFromHeight = 0xC7,
    KeywordSpringToFocus = 0xC8,
    KeywordEndUncollidable = 0xC9,
    KeywordFromStart = 0xCA,
    KeywordUnusedCB = 0xCB,
    KeywordShareKeys = 0xCC,
    KeywordOwnPosition = 0xCD,
    KeywordLinkedById = 0xCE,
    KeywordSharePaths = 0xD0,
    KeywordPushedByVolumes = 0xD1,
    KeywordNearest = 0xD2,
    KeywordOnPath = 0xD3,
    KeywordOffPath = 0xD4,
    KeywordOnImpact = 0xD5,
    KeywordOnHardImpact = 0xD7,
    KeywordOnScrape = 0xD9,
    KeywordPlaceFollowCamera = 0xDB,
    KeywordMirrored = 0xDC,
    KeywordNoFraming = 0xDD,
    KeywordVisibleOnly = 0xDE,
    KeywordNearestOnly = 0xDF,
    KeywordLevel = 0xE0,
    KeywordSteerInstance = 0xE1,
    KeywordSteerFacing = 0xE2,
    KeywordIgnoreNoises = 0xE3,
    KeywordEveryLinked = 0xE6,
    KeywordOnStep = 0xE7,
    KeywordOnOtherStep = 0xE8,
    // A particle trail a runner's end takes away even when its node keeps its particles (TrailBits::removalKind 1); 0xEA gives
    // a kind nothing takes away
    KeywordEndsWithRunner = 0xE9,
    KeywordUnusedEA = 0xEA,
    KeywordReset = 0xEB,
    KeywordRed = 0xEC,
    KeywordGreen = 0xED,
    KeywordBlue = 0xEE,
    KeywordCyan = 0xEF,
    KeywordMagenta = 0xF0,
    KeywordYellow = 0xF1,
    KeywordBlack = 0xF2,
    KeywordWhite = 0xF3,
    KeywordBottomCentre = 0xF4,
    KeywordArc = 0xF5,
    KeywordSmooth = 0xF6,
    KeywordOnLand = 0xF7,
    KeywordContinue = 0xF8,
    KeywordAlwaysQueued = 0xF9,
    KeywordCutsceneRig = 0xFA,
    KeywordNoSource = 0xFB,
    KeywordInOrder = 0xFC,
    KeywordKeep = 0xFD,
    // The first and the last of the reverb types (SetReverb's: the keyword's offset from the first is ReverbBits::type)
    KeywordFirstReverb = 0xFE,
    KeywordLastReverb = 0x106,
    KeywordBoxReverb = 0x10A,
    KeywordNeverPutBack = 0x10B,
    KeywordGravityFrame = 0x10C,
    KeywordShadowTaperedCylinder = 0x10D,
    KeywordShadowTaperedRoundedCube = 0x10E,
    KeywordShadowTaperedCube = 0x10F,
    KeywordShadowTaperedOctagon = 0x110,
    KeywordOnce = 0x111,
    KeywordNoSurfaceSound = 0x112,
    KeywordToContact = 0x113,
    KeywordContactSoundsOff = 0x114,
    KeywordPositionRate = 0x115,
    KeywordYawSpeed = 0x116,
    KeywordCameraPitch = 0x117,
    KeywordCameraDistance = 0x118,
    KeywordCameraYaw = 0x119,
    KeywordCameraFov = 0x11A,
    KeywordEmitter = 0x11C,
    KeywordParent = 0x11D,
    KeywordSameRank = 0x11F,
    KeywordBelowTriggerRank = 0x120,
    KeywordUpToTriggerRank = 0x121,
    KeywordTriggerRank = 0x122,
    KeywordFirstWeapon = 0x123,
    KeywordSecondWeapon = 0x124,
    KeywordThirdWeapon = 0x125,
    KeywordUngrouped = 0x126,
    KeywordOwnObject = 0x127,
    KeywordAddAgain = 0x128,

    // The tool's custom ones and the game's after them
    KeywordGameDummy = 0x200,
    KeywordHitWalls = 0x201,
    KeywordHitFloor = 0x202,
    KeywordHitRoof = 0x203,
    KeywordNoCrates = 0x204,
    KeywordNoCreatures = 0x205,
    KeywordNoCharacters = 0x206,
    KeywordNoFurniture = 0x207,
    KeywordNoPlayers = 0x208,
    KeywordNoPickups = 0x209,
    KeywordNoFoofie = 0x20A,
    KeywordNoChiChi = 0x20B,
    KeywordNoPayGates = 0x20C,
    KeywordGetCrates = 0x20D,
    KeywordGetCreatures = 0x20E,
    KeywordGetCharacters = 0x20F,
    KeywordGetFurniture = 0x210,
    KeywordGetPlayers = 0x211,
    KeywordGetPickups = 0x212,
    KeywordGetFoofie = 0x213,
    KeywordGetChiChi = 0x214,
    KeywordGetPayGates = 0x215,
    KeywordFirstHull = 0x216,
    KeywordNoFlights = 0x217,
    KeywordNoLongJumps = 0x218,
    KeywordNoHighJumps = 0x219,
    KeywordNoPathFlag6 = 0x21A,
    KeywordHitExplosion = 0x21B,
    KeywordHitFallingThrough = 0x21C,
    KeywordHitBurning = 0x21D,
    KeywordHitIceteroid = 0x21E,
    KeywordHitProjectile = 0x21F,
    KeywordHitKind6 = 0x220,
    KeywordHitElectric = 0x221,
    KeywordHitKind8 = 0x222,
    KeywordHitGeneric = 0x223,
    KeywordHitCrush = 0x224,
    KeywordHitKind12 = 0x225,
    KeywordHitKind13 = 0x226,
    KeywordHitKind14 = 0x227,
    KeywordHitBite = 0x228,
    KeywordHitSpin = 0x229,
    KeywordHitKick = 0x22A,
    KeywordHitKind18 = 0x22B,
    KeywordHitHeavy = 0x22C,
    KeywordHitKind21 = 0x22D,
    KeywordHitKind22 = 0x22E,
    KeywordHitSinking = 0x22F,
    KeywordGetProjectiles = 0x230,
    KeywordNoProjectiles = 0x231,
    KeywordCrash = 0x232,
    KeywordCortex = 0x233,
    KeywordNina = 0x234,
    KeywordTallCrash = 0x235,
    KeywordHitKneeDrop = 0x236,
    KeywordNoPathFlag7 = 0x237,
    KeywordNoPathFlag8 = 0x238,
    KeywordNoPlainPaths = 0x239,
    KeywordNoJumps = 0x23A,
    KeywordOnlyPathFlag6 = 0x23B,
    KeywordOnlyFlights = 0x23C,
    KeywordPlainAndJumpsOnly = 0x23D,
    KeywordEndUnflagged = 0x23E,
    KeywordEndAlwaysTaken = 0x23F,
    KeywordEndAirborne = 0x240,
    KeywordEndFlag4 = 0x241,
    KeywordEndFlag6 = 0x242,
    KeywordOnlyCharacters = 0x245,
    KeywordStartUnflagged = 0x24D,
    KeywordStartAlwaysTaken = 0x24E,
    KeywordStartAirborne = 0x24F,
    KeywordStartFlag4 = 0x250,
    KeywordStartFlag6 = 0x251,
    KeywordKeepCurrent = 0x252,
    KeywordFixedYaw145 = 0x253,
    KeywordFixedYaw15 = 0x254,
    KeywordFixedYaw180 = 0x255,
    KeywordFixedYaw90 = 0x256,
    KeywordShot0 = 0x257,
    KeywordShot1 = 0x258,
    KeywordShot2 = 0x259,
    KeywordShot3 = 0x25A,
    KeywordShot4 = 0x25B,
    KeywordShot5 = 0x25C,
    KeywordShot6 = 0x25D,
    KeywordShot7 = 0x25E,
    KeywordNoFramingAngles = 0x25F,
    KeywordFramingSixth = 0x260,
    KeywordFramingThird = 0x261,
    KeywordFollowCamera = 0x262,
    KeywordGameRig = 0x263,
    KeywordAimFirst = 0x264,
    KeywordAimSecond = 0x265,
    KeywordAimBetween = 0x266,
    KeywordFramingHalf = 0x267,
    KeywordDistanceFromFirst = 0x268,
    KeywordDistanceFromSecond = 0x269,
    KeywordNoFixedYaw = 0x26A,
    KeywordEaseIn = 0x26B,
    KeywordEaseOut = 0x26C,
    KeywordUnused26D = 0x26D,
    KeywordUnused26E = 0x26E,
    // The first of the areas (TokenArea)
    KeywordFirstArea = 0x26F,
    // The first of the gems (TokenGem)
    KeywordFirstGem = 0x288,
    // The first of the player modes (TokenPlayerMode)
    KeywordFirstPlayerMode = 0x291,
    KeywordBoardControls = 0x297,
    KeywordNoBounce = 0x299,
    KeywordJointAimController = 0x29A,
    KeywordMaskController = 0x29B,
    KeywordSplineController = 0x29C,
    KeywordSkateController = 0x29D,
    KeywordMecha = 0x29E,
};

// What a token's value is
enum ScriptTokenType : u8
{
    TokenFloat = 0,
    TokenInt = 1,
    TokenKeyword = 4,
    // An instance property's index
    TokenProperty = 10,
};

// The commands' two bit switches a token turns on or off (3 leaves them as well)
enum SwitchSetting : u32
{
    SwitchLeft = 0,
    SwitchOn = 1,
    SwitchOff = 2,
};

struct ScriptToken
{
    u16 tag;
    u8 type;
    u8 unused03;
    u32 value;

    f32 Float() const
    {
        return *reinterpret_cast<const f32*>(&value);
    }
};
CHECK_SIZE(ScriptToken, 8);

// A list of tokens: its disk manager block and how many it has
struct ScriptTokenList
{
    s32 block;
    u32 count;
};

// A walk over a token list (its vtable: 1 the destructor, 2 to the first, 3 whether it's past the last, 4 the token, 5 to the
// next; its base's are abstract), the list, its tokens in the disk manager's memory and the index. The same class again under
// another vtable has its own copies of the functions
struct ScriptTokenReader
{
    const GccVTableEntry* vtable;
    const ScriptTokenList* list;
    const ScriptToken* tokens;
    u32 index;

    static ScriptTokenReader* Construct(ScriptTokenReader* reader, const ScriptTokenList* list) RETAIL(DiskDataReader_Init);
    void Destroy(u32 destroyFlags) RETAIL(FUN_00208338);
    void First() RETAIL(FUN_002087f8);
    bool AtEnd() const RETAIL(DiskDataReader_AtEnd);
    const ScriptToken* Current() const RETAIL(GetCurrentPosition);
    void Next() RETAIL(DiskDataReader_Next);
    void BaseDestroy(u32 destroyFlags) RETAIL(FUN_0011f068);
    void OtherDestroy(u32 destroyFlags) RETAIL(FUN_00208308);
    void OtherBaseDestroy(u32 destroyFlags) RETAIL(FUN_00209e70);
    void OtherFirst() RETAIL(FUN_00208750);
    bool OtherAtEnd() const RETAIL(FUN_00208770);
    const ScriptToken* OtherCurrent() const RETAIL(FUN_00208758);
    void OtherNext() RETAIL(FUN_00208788);
};
CHECK_SIZE(ScriptTokenReader, 0x10);

extern "C"
{
    // A tagged value given a token's value as its type has it (a property reference whatever its type, an angle's degrees made
    // 65536ths of a turn)
    void ParseTaggedValueRecord(const ScriptToken* token, TaggedValue* value) RETAIL(ParseTaggedValueRecord);
}

// Helpers the commands' parsers share
extern "C"
{
    // A token's switch (SwitchOn for KeywordOn, SwitchOff for anything else), and whether its value is KeywordOn
    u32 TokenSetting(const ScriptToken* token) RETAIL(FUN_00208510);
    bool TokenIsOn(const ScriptToken* token) RETAIL(FUN_002084f0);
    // TokenIsOn again (the same code at another address)
    bool TokenIsOn2(const ScriptToken* token) RETAIL(FUN_00208500);
    // The designator a token names (a keyword's, TagAgent's value, TagKey's less one) and the space a keyword names, the one given
    // when it names none
    u32 TokenDesignator(const ScriptToken* token, u32 designator) RETAIL(FUN_00208528);
    u32 TokenSpace(const ScriptToken* token, u32 space) RETAIL(FUN_00208550);
    // What they read: the designator or the space set when the token names one
    void ParseDesignatorToken(const ScriptToken* token, u32* designator) RETAIL(FUN_002066a0);
    void ParseSpaceToken(const ScriptToken* token, u32* space) RETAIL(FUN_002085c0);
    // A tagged value from a whole list of tokens: TagDegreesPerSecond makes it an angle, TagMetresPerSecond a float, and gives it
    // the token's value
    void ParseTaggedValueTokens(const ScriptTokenList* tokens, TaggedValue* value) RETAIL(ParseTaggedValueTokens);
    // TagX, TagY and TagZ set a vector's x, y and z
    void TokenVectorComponent(const ScriptToken* token, f32* vector) RETAIL(FUN_00208578);
    // The tokens of a motion block's arguments (the springy contacts' and the launches') read into it: a body's values, kind,
    // constraint, bits and centre of mass
    void ParseMotionBlockTokens(const ScriptTokenList* tokens, MotionBlock* block) RETAIL(FUN_00205fe8);
    // The character a keyword names (KeywordCrash to KeywordTallCrash), GameProgress::NoCharacter for any other
    u32 TokenCharacter(u32 token) RETAIL(FUN_0013fe60);
    // The head tracking settings' limits of its turn (game/objectnode.h's HeadTrackingSettings) made from degrees: the pitch's
    // either way, with the negative one's sine in the y direction and minus the positive one's in x, and the yaw's, with its cosine
    // in z (which also sets the bits' unused27)
    void SetHeadTrackingNegativePitch(void* settings, f32 degrees) RETAIL_N32(FUN_0023ee18);
    void SetHeadTrackingPositivePitch(void* settings, f32 degrees) RETAIL_N32(FUN_0023edd0);
    void SetHeadTrackingYawLimit(void* settings, f32 degrees) RETAIL_N32(FUN_0023ee60);
}
